services:
  message-buffer:
    image: armandocastro/message-buffer:latest
    container_name: message-buffer
    environment:
      - SERVICE_URL_BUFFER_3000
      - PORT=3000
      - ACCESS_TOKEN=meu-token-super-seguro
      - DATABASE_URL=postgres://message_buffer:message_buffer@db:5432/message_buffer
      - REDIS_URL=redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: message-buffer-db
    environment:
      - POSTGRES_USER=message_buffer
      - POSTGRES_PASSWORD=message_buffer
      - POSTGRES_DB=message_buffer
    volumes:
      - message-buffer-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U message_buffer"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: message-buffer-redis
    volumes:
      - message-buffer-redisdata:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  message-buffer-pgdata:
  message-buffer-redisdata:
